DROP TABLE IF EXISTS "account" CASCADE;
DROP TABLE IF EXISTS "coin" CASCADE;
DROP TABLE IF EXISTS "price_history" CASCADE;
DROP TABLE IF EXISTS "session" CASCADE;
DROP TABLE IF EXISTS "transaction" CASCADE;
DROP TABLE IF EXISTS "user" CASCADE;
DROP TABLE IF EXISTS "user_portfolio" CASCADE;
DROP TABLE IF EXISTS "verification" CASCADE;
